# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    container_name: postgres
    image: docker.io/bitnami/postgresql:11
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=desafio
      - POSTGRESQL_PASSWORD=desafio
      - POSTGRESQL_DATABASE=db_desafio
    networks:
      - desafio_network
networks:
  desafio_network:

volumes:
  postgresql_data:
  pgadmin:
