version: "3.9"
services:

  fpm:
    build:
      context: ./docker
    volumes:
      - .:/var/www

  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - fpm
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  pgsql:
    image: postgres
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: desafio
      POSTGRES_DB: desafio
      POSTGRES_USER: desafio
      PGDATA: /var/lib/postgresql/data

  master:
    build:
      context: ./docker/locust
    ports:
      - "8089:8089"
    depends_on:
      - web
    volumes:
      - ./docker/locust/locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master -H http://web

  worker:
    build:
      context: ./docker/locust
    volumes:
      - ./docker/locust/locustfile.py:/mnt/locust/locustfile.py
    depends_on:
      - web
    command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
  pgdata:
    driver: "local"
